name: Build Sokora

on:
  push:
    branches:
      - dev

jobs:
  build:
    if: github.repository == 'SokoraDesu/Sokora'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages and build
        run: bun install && bunx tsc -b ./
